evqa:
  fixed:
    EchoSight: outputs/raw_methods/evqa/fixed/EchoSight.jsonl
    IBA: outputs/raw_methods/evqa/fixed/IBA.jsonl
    CoMEM: outputs/raw_methods/evqa/fixed/CoMEM.jsonl
    ReflectiVA: outputs/raw_methods/evqa/fixed/ReflectiVA.json
    Wiki-PRF: outputs/raw_methods/evqa/fixed/Wiki_PRF.jsonl
  unfixed:
    EchoSight: outputs/raw_methods/evqa/unfixed/EchoSight.jsonl
    IBA: outputs/raw_methods/evqa/unfixed/IBA.jsonl
    CoMEM: outputs/raw_methods/evqa/unfixed/CoMEM.jsonl
    ReflectiVA: outputs/raw_methods/evqa/unfixed/ReflectiVA.json
    Wiki-PRF: outputs/raw_methods/evqa/unfixed/Wiki_PRF.jsonl
infoseek:
  fixed:
    EchoSight: outputs/raw_methods/infoseek/fixed/EchoSight.jsonl
    IBA: outputs/raw_methods/infoseek/fixed/IBA.jsonl
    CoMEM: outputs/raw_methods/infoseek/fixed/CoMEM.jsonl
    ReflectiVA: outputs/raw_methods/infoseek/fixed/ReflectiVA
    Wiki-PRF: outputs/raw_methods/infoseek/fixed/Wiki_PRF.jsonl
  unfixed:
    EchoSight: outputs/raw_methods/infoseek/unfixed/EchoSight.jsonl
    IBA: outputs/raw_methods/infoseek/unfixed/IBA.jsonl
    CoMEM: outputs/raw_methods/infoseek/unfixed/CoMEM.jsonl
    ReflectiVA: outputs/raw_methods/infoseek/unfixed/ReflectiVA
    Wiki-PRF: outputs/raw_methods/infoseek/unfixed/Wiki_PRF.jsonl
